//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBoardPlatform.PL.Localization.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobBoardPlatform.PL.Localization.Text.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search_Text {
            get {
                return ResourceManager.GetString("Button_Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search e.g. skill, location, company.
        /// </summary>
        public static string Field_Search_Placeholder_Text {
            get {
                return ResourceManager.GetString("Field_Search_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your next job in game development.
        /// </summary>
        public static string Navbar_Title {
            get {
                return ResourceManager.GetString("Navbar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string OfferType_Commission {
            get {
                return ResourceManager.GetString("OfferType_Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment.
        /// </summary>
        public static string OfferType_Employment {
            get {
                return ResourceManager.GetString("OfferType_Employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Technology_Widget_All {
            get {
                return ResourceManager.GetString("Technology_Widget_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Technology_Widget_Audio {
            get {
                return ResourceManager.GetString("Technology_Widget_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics 3D.
        /// </summary>
        public static string Technology_Widget_Graphics3D {
            get {
                return ResourceManager.GetString("Technology_Widget_Graphics3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Design.
        /// </summary>
        public static string Technology_Widget_LevelDesign {
            get {
                return ResourceManager.GetString("Technology_Widget_LevelDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        public static string Technology_Widget_Programming {
            get {
                return ResourceManager.GetString("Technology_Widget_Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string Toggle_Remote_Text {
            get {
                return ResourceManager.GetString("Toggle_Remote_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With salary.
        /// </summary>
        public static string Toggle_With_Salary_Text {
            get {
                return ResourceManager.GetString("Toggle_With_Salary_Text", resourceCulture);
            }
        }
    }
}
