name: "Build and Deploy"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env:
  AZURE_WEBAPP_NAME: game-dev-careers
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  WEBAPP_SOLUTION_PATH: './JobBoardPlatform/JobBoardPlatform.sln'
  NETCORE_VERSION: '6.x.x'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    
    - name: Restore packages
      run: dotnet restore ${{ env.WEBAPP_SOLUTION_PATH }}

    - name: Build app
      run: dotnet build ${{ env.WEBAPP_SOLUTION_PATH }} --configuration Release --no-restore

    - name: Publish app for deploy
      run: dotnet publish ${{ env.WEBAPP_SOLUTION_PATH }} --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
